# Setup
title:               lmdolphy
tagline:             'Explore broader, dive deeper'
description:         'Studied econ, worked as a tax consultant, now diving into programming and more. Hello World from Yunhan''s personal blog!'
#url:                 https://yunhan-zheng.github.io/lmdolphy
baseurl:             /lmdolphy
paginate:            5

# About/contact
author:
  name:              Yunhan Zheng
  url:               
  email:             yunhan.zheng@hotmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]